name: openai-question

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Prompt to generate question'
        required: true

jobs:
  ask:
    runs-on: ubuntu-latest
    steps:
      - name: Query OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPT: ${{ inputs.prompt }}
        run: |
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{"model":"gpt-4o-mini","messages":[{"role":"system","content":"You are an expert hardware engineering interviewer. Return JSON with fields question, choices (array of 4 strings), answer (0-3), explanation."},{"role":"user","content":"'"$PROMPT"'"}],"max_tokens":300}')
          echo "$RESPONSE" > response.json
      - name: Upload response
        uses: actions/upload-artifact@v4
        with:
          name: openai-response
          path: response.json
